#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Draws Glowbar Disco's launcher icon: the four-colour Glowbar, lit, on black.

One geometry, two outputs: the adaptive icon's vector drawables (res/drawable/ic_launcher_*.xml) and an SVG of the
whole icon for previews. Run it after changing anything here (`./dc icon` also redraws the README's picture):

    tools/icon.py                  # rewrite the three drawables
    tools/icon.py --svg out.svg    # also write a preview (108 x 108, unmasked)
"""
import sys
from pathlib import Path

RES = Path(__file__).resolve().parent.parent / "app/src/main/res/drawable"

BLUE, RED, YELLOW, GREEN = "#4285F4", "#EA4335", "#FBBC04", "#34A853"
X0, X1 = 31.0, 77.0                   # the bar, centred, well inside the 66 dp safe circle
Y0, Y1 = 50.5, 57.5
GLOW = 26.0                           # how far each segment's light reaches sideways
FLAT = 0.6                            # and how much flatter it is than it is wide


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def segments():
    """The bar's four segments as (left, right, colour), blue to green as on the lid."""
    w = (X1 - X0) / 4
    return [(X0 + i * w, X0 + (i + 1) * w, col) for i, col in enumerate((BLUE, RED, YELLOW, GREEN))]


def rect(x0, y0, x1, y1, left=False, right=False):
    """A rectangle; with left or right, that end is a half circle."""
    r = (y1 - y0) / 2
    d = f"M{f(x0)},{f(y0)}H{f(x1)}"
    d += f"A{f(r)},{f(r)} 0,0 1,{f(x1)},{f(y1)}" if right else f"V{f(y1)}"
    d += f"H{f(x0)}"
    d += f"A{f(r)},{f(r)} 0,0 1,{f(x0)},{f(y0)}" if left else f"V{f(y0)}"
    return d + "Z"


def circle(cx, cy, r):
    return f"M{f(cx - r)},{f(cy)}A{f(r)},{f(r)} 0,1 1,{f(cx + r)},{f(cy)}A{f(r)},{f(r)} 0,1 1,{f(cx - r)},{f(cy)}Z"


# Shapes are dicts: d, and fill (a colour, alpha), or radial (cx, cy, r, stops) or linear (x0, y0, x1, y1, stops), with
# stops as [(offset, colour, alpha)]; squash=(pivot y, factor) flattens one vertically.
def foreground():
    cy = (Y0 + Y1) / 2
    segs = segments()
    shapes = []
    # Each segment's light, an ellipse of its colour around it.
    for x0, x1, col in segs:
        cx = (x0 + x1) / 2
        shapes.append(dict(d=circle(cx, cy, GLOW), squash=(cy, FLAT), radial=(cx, cy, GLOW,
                           [(0, col, 0.9), (0.18, col, 0.55), (0.45, col, 0.16), (0.75, col, 0.04), (1, col, 0)])))
    # The bar.
    shapes += [dict(d=rect(x0, Y0, x1, Y1, left=i == 0, right=i == 3), fill=col) for i, (x0, x1, col) in enumerate(segs)]
    # A sheen along its top edge, as on a lit glass bar.
    shapes.append(dict(d=rect(X0, Y0, X1, Y1, left=True, right=True),
                       linear=(0, Y0, 0, Y1, [(0, "#FFFFFF", 0.45), (0.35, "#FFFFFF", 0.0), (1, "#000000", 0.12)])))
    return shapes


def monochrome():
    """The themed icon: the bar alone, in one colour (the launcher tints it)."""
    return [dict(d=rect(X0, Y0, X1, Y1, left=True, right=True), fill="#FFFFFF")]


BACKGROUND = [dict(d="M0,0h108v108h-108z", linear=(54, 0, 54, 108, [(0, "#0C0C0F", 1), (1, "#000000", 1)]))]


def argb(col, alpha=1.0):
    return f"#{round(alpha * 255):02X}{col[1:]}"


def vector(shapes, comment):
    out = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {comment} Generated by tools/icon.py: edit that, not this. -->",
           '<vector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt"',
           '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">']
    for s in shapes:
        ind = "    "
        if "squash" in s:
            py, k = s["squash"]
            out.append(f'    <group android:pivotY="{f(py)}" android:scaleY="{f(k)}">')
            ind = "        "
        if "fill" in s:
            out.append(f'{ind}<path android:fillColor="{argb(s["fill"], s.get("alpha", 1))}" android:pathData="{s["d"]}" />')
        else:
            out.append(f'{ind}<path android:pathData="{s["d"]}">')
            out.append(f'{ind}    <aapt:attr name="android:fillColor">')
            if "linear" in s:
                x0, y0, x1, y1, stops = s["linear"]
                out.append(f'{ind}        <gradient android:type="linear" android:startX="{f(x0)}" android:startY="{f(y0)}"'
                           f' android:endX="{f(x1)}" android:endY="{f(y1)}">')
            else:
                cx, cy, r, stops = s["radial"]
                out.append(f'{ind}        <gradient android:type="radial" android:centerX="{f(cx)}" android:centerY="{f(cy)}"'
                           f' android:gradientRadius="{f(r)}">')
            out += [f'{ind}            <item android:offset="{f(o)}" android:color="{argb(c, a)}" />' for o, c, a in stops]
            out.append(f"{ind}        </gradient>")
            out.append(f"{ind}    </aapt:attr>")
            out.append(f"{ind}</path>")
        if "squash" in s:
            out.append("    </group>")
    out.append("</vector>")
    return "\n".join(out) + "\n"


def svg(layers):
    defs, body = [], []
    for s in [s for shapes in layers for s in shapes]:
        if "fill" in s:
            el = f'<path d="{s["d"]}" fill="{s["fill"]}" fill-opacity="{f(s.get("alpha", 1))}"/>'
        else:
            gid = f"g{len(defs)}"
            if "linear" in s:
                x0, y0, x1, y1, stops = s["linear"]
                head = f'<linearGradient id="{gid}" gradientUnits="userSpaceOnUse" x1="{f(x0)}" y1="{f(y0)}" x2="{f(x1)}" y2="{f(y1)}">'
                tail = "</linearGradient>"
            else:
                cx, cy, r, stops = s["radial"]
                head = f'<radialGradient id="{gid}" gradientUnits="userSpaceOnUse" cx="{f(cx)}" cy="{f(cy)}" r="{f(r)}">'
                tail = "</radialGradient>"
            defs.append(head + "".join(f'<stop offset="{f(o)}" stop-color="{c}" stop-opacity="{f(a)}"/>'
                                       for o, c, a in stops) + tail)
            el = f'<path d="{s["d"]}" fill="url(#{gid})"/>'
        if "squash" in s:
            py, k = s["squash"]
            el = f'<g transform="translate(0,{f(py)}) scale(1,{f(k)}) translate(0,{f(-py)})">{el}</g>'
        body.append(el)
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="108" height="108">'
            f'<defs>{"".join(defs)}</defs>{"".join(body)}</svg>\n')


def main(argv):
    (RES / "ic_launcher_background.xml").write_text(vector(BACKGROUND, "Black, a touch lighter at the top."))
    (RES / "ic_launcher_foreground.xml").write_text(
        vector(foreground(), "The Glowbar, lit: four segments, each with its light around it."))
    (RES / "ic_launcher_monochrome.xml").write_text(
        vector(monochrome(), "Themed icon: the bar in one colour (the launcher tints it)."))
    if "--svg" in argv:
        Path(argv[argv.index("--svg") + 1]).write_text(svg([BACKGROUND, foreground()]))
        if "--mono" in argv:
            Path(argv[argv.index("--mono") + 1]).write_text(
                svg([[dict(BACKGROUND[0], linear=(0, 0, 0, 108, [(0, "#2A3A55", 1), (1, "#2A3A55", 1)]))], monochrome()]))


if __name__ == "__main__":
    main(sys.argv[1:])
